#!/bin/sh

DRIVER_VIAS=/mnt/driver_agujas.o
MAJORN_VIAS=251
MINORN_AGUJAS=0
DEVFIL_AGUJAS=/var/agujas

MINORN_VIA_A=1
DEVFIL_VIA_A=/var/viaA

MINORN_VIA_B=2
DEVFIL_VIA_B=/var/viaB

insmod $DRIVER_VIAS
mknod $DEVFIL_AGUJAS c $MAJORN_VIAS $MINORN_AGUJAS
chmod 755 $DEVFIL_AGUJAS

mknod $DEVFIL_VIA_A c $MAJORN_VIAS $MINORN_VIA_A
chmod 755 $DEVFIL_VIA_A

mknod $DEVFIL_VIA_B c $MAJORN_VIAS $MINORN_VIA_B
chmod 755 $DEVFIL_VIA_B
